name: Gills
author: Falkirks
version: 2.0.0
api: [1.7.0]
main: gills\Gills
commands:
 gills:
  permission: gills.command
  description: Control other players
  usage: /gills [name]
permissions:
 gills:
  default: false
  children:
   gills.command:
    default: op
   gills.breath:
    default: false